# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-29 18:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=45)),
                ('completed', models.BooleanField(default=False)),
                ('order', models.IntegerField(null=True)),
            ],
        ),
    ]
